PREFIX ub:<http://swat.cse.lehigh.edu/onto/univ-bench.owl#>
SELECT ?X
WHERE {  
	?X a ub:Publication .
 	?X ub:publicationAuthor ?Y .
  	?Y a ub:Professor .
   	?X ub:publicationAuthor ?Z .
   	?Z a ub:Student .
}